version: '3.1'

services:

  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: iamhello-postgres
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    hostname: adminer
    restart: unless-stopped
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    image: iamhello-redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
        REDIS_PASSWORD: qwerty
    hostname: redis
    restart: unless-stopped
    networks:
      - app-network


  nestjs:
    build:
      context: .
      dockerfile: nestjs.dockerfile
    image: iamhello-nestjs
    container_name: nestjs
    hostname: nestjs
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - app-network

  webserver:
    build:
        context: .
        dockerfile: webserver.dockerfile
    image: iamhello-webserver
    container_name: webserver
    hostname: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nestjs
    networks:
      - app-network

  certbot:
    build:
      context: .
      dockerfile: certbot.dockerfile
    image: iamhello-certbot
    container_name: certbot
    hostname: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email the-travnik@ya.ru --agree-tos --no-eff-email --staging -d 88503.hosted-by-virtualdc.ru
    networks:
      - app-network

volumes:
  postgres-data:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:

networks:
  app-network:
    driver: bridge
